Map<String, dynamic> responseData = {
  "id": 96,
  "accountNo": "MSA000000096",
  "depositType": {
    "id": 100,
    "code": "depositAccountType.savingsDeposit",
    "value": "Savings"
  },
  "clientId": 114,
  "clientName": "Tabbitha Mutinda",
  "savingsProductId": 1,
  "savingsProductName": "M-SOMA AVAILABLE",
  "fieldOfficerId": 0,
  "status": {
    "id": 300,
    "code": "savingsAccountStatusType.active",
    "value": "Active",
    "submittedAndPendingApproval": false,
    "approved": false,
    "rejected": false,
    "withdrawnByApplicant": false,
    "active": true,
    "closed": false,
    "prematureClosed": false,
    "transferInProgress": false,
    "transferOnHold": false,
    "matured": false
  },
  "subStatus": {
    "id": 0,
    "code": "SavingsAccountSubStatusEnum.none",
    "value": "None",
    "none": true,
    "inactive": false,
    "dormant": false,
    "escheat": false,
    "block": false,
    "blockCredit": false,
    "blockDebit": false
  },
  "timeline": {
    "submittedOnDate": [2022, 7, 27],
    "submittedByUsername": "mifos",
    "submittedByFirstname": "App",
    "submittedByLastname": "Administrator",
    "approvedOnDate": [2022, 7, 27],
    "approvedByUsername": "mifos",
    "approvedByFirstname": "App",
    "approvedByLastname": "Administrator",
    "activatedOnDate": [2022, 7, 27],
    "activatedByUsername": "mifos",
    "activatedByFirstname": "App",
    "activatedByLastname": "Administrator"
  },
  "currency": {
    "code": "KES",
    "name": "Kenyan Shilling",
    "decimalPlaces": 2,
    "inMultiplesOf": 1,
    "displaySymbol": "KSh",
    "nameCode": "currency.KES",
    "displayLabel": "Kenyan Shilling (KSh)"
  },
  "nominalAnnualInterestRate": 0.000000,
  "interestCompoundingPeriodType": {
    "id": 1,
    "code":
        "savings.interest.period.savingsCompoundingInterestPeriodType.daily",
    "value": "Daily"
  },
  "interestPostingPeriodType": {
    "id": 4,
    "code":
        "savings.interest.posting.period.savingsPostingInterestPeriodType.monthly",
    "value": "Monthly"
  },
  "interestCalculationType": {
    "id": 1,
    "code": "savingsInterestCalculationType.dailybalance",
    "value": "Daily Balance"
  },
  "interestCalculationDaysInYearType": {
    "id": 365,
    "code": "savingsInterestCalculationDaysInYearType.days365",
    "value": "365 Days"
  },
  "withdrawalFeeForTransfers": true,
  "allowOverdraft": false,
  "enforceMinRequiredBalance": false,
  "withHoldTax": false,
  "lastActiveTransactionDate": [2022, 8, 8],
  "isDormancyTrackingActive": true,
  "daysToInactive": 19,
  "daysToDormancy": 49,
  "daysToEscheat": 79,
  "summary": {
    "currency": {
      "code": "KES",
      "name": "Kenyan Shilling",
      "decimalPlaces": 2,
      "inMultiplesOf": 1,
      "displaySymbol": "KSh",
      "nameCode": "currency.KES",
      "displayLabel": "Kenyan Shilling (KSh)"
    },
    "totalDeposits": 16.000000,
    "totalWithdrawals": 12.000000,
    "totalInterestPosted": 0,
    "accountBalance": 4.000000,
    "totalOverdraftInterestDerived": 0,
    "interestNotPosted": 0,
    "availableBalance": 4.000000
  },
  "transactions": [
    {
      "id": 311,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 8],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 4.000000,
      "reversed": false,
      "transfer": {
        "id": 74,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 8],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 8, 8],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 309,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 8],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 5.000000,
      "reversed": false,
      "transfer": {
        "id": 73,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 8],
        "transferDescription": "Pay fees"
      },
      "submittedOnDate": [2022, 8, 8],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 307,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 8],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 6.000000,
      "reversed": false,
      "transfer": {
        "id": 72,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 8],
        "transferDescription": "Savings "
      },
      "submittedOnDate": [2022, 8, 8],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 294,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 5],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "paymentDetailData": {
        "id": 294,
        "paymentType": {"id": 1, "name": "M-PESA  C2B"},
        "accountNumber": "254740918285",
        "checkNumber": "",
        "routingCode": "",
        "receiptNumber": "QH50OWXAII",
        "bankNumber": ""
      },
      "amount": 1.000000,
      "runningBalance": 7.000000,
      "reversed": false,
      "submittedOnDate": [2022, 8, 5],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 292,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 4],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "paymentDetailData": {
        "id": 292,
        "paymentType": {"id": 1, "name": "M-PESA  C2B"},
        "accountNumber": "254740918285",
        "checkNumber": "",
        "routingCode": "",
        "receiptNumber": "QH49NA9UEX",
        "bankNumber": ""
      },
      "amount": 1.000000,
      "runningBalance": 6.000000,
      "reversed": false,
      "submittedOnDate": [2022, 8, 4],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 289,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 3],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 5.000000,
      "reversed": false,
      "transfer": {
        "id": 70,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 3],
        "transferDescription": "Savings "
      },
      "submittedOnDate": [2022, 8, 3],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 287,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 3],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 6.000000,
      "reversed": false,
      "transfer": {
        "id": 69,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 3],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 8, 3],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 284,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 3],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 7.000000,
      "reversed": false,
      "transfer": {
        "id": 68,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 3],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 8, 3],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 281,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 2],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 8.000000,
      "reversed": false,
      "transfer": {
        "id": 67,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 2],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 8, 2],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 279,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 2],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 9.000000,
      "reversed": false,
      "transfer": {
        "id": 66,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 2],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 8, 2],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 278,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 2],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "paymentDetailData": {
        "id": 278,
        "paymentType": {"id": 1, "name": "M-PESA  C2B"},
        "accountNumber": "254740918285",
        "checkNumber": "",
        "routingCode": "",
        "receiptNumber": "QH25IMPKXR",
        "bankNumber": ""
      },
      "amount": 1.000000,
      "runningBalance": 10.000000,
      "reversed": false,
      "submittedOnDate": [2022, 8, 2],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 276,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 2],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 9.000000,
      "reversed": false,
      "transfer": {
        "id": 65,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 8, 2],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 8, 2],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 275,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 8, 1],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "paymentDetailData": {
        "id": 275,
        "paymentType": {"id": 1, "name": "M-PESA  C2B"},
        "accountNumber": "254740918285",
        "checkNumber": "",
        "routingCode": "",
        "receiptNumber": "QH11GU8PGB",
        "bankNumber": ""
      },
      "amount": 1.000000,
      "runningBalance": 10.000000,
      "reversed": false,
      "submittedOnDate": [2022, 8, 1],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 271,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 7, 29],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "paymentDetailData": {
        "id": 271,
        "paymentType": {"id": 1, "name": "M-PESA  C2B"},
        "accountNumber": "254740918285",
        "checkNumber": "",
        "routingCode": "",
        "receiptNumber": "QGT5AD8GH1",
        "bankNumber": ""
      },
      "amount": 1.000000,
      "runningBalance": 9.000000,
      "reversed": false,
      "submittedOnDate": [2022, 7, 29],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 258,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 7, 27],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "paymentDetailData": {
        "id": 258,
        "paymentType": {"id": 1, "name": "M-PESA  C2B"},
        "accountNumber": "254740918285",
        "checkNumber": "",
        "routingCode": "",
        "receiptNumber": "QGR570JTRX",
        "bankNumber": ""
      },
      "amount": 1.000000,
      "runningBalance": 8.000000,
      "reversed": false,
      "submittedOnDate": [2022, 7, 27],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 254,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 7, 27],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 7.000000,
      "reversed": false,
      "transfer": {
        "id": 62,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 7, 27],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 7, 27],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 252,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 7, 27],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 8.000000,
      "reversed": false,
      "transfer": {
        "id": 61,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 7, 27],
        "transferDescription": "Savings "
      },
      "submittedOnDate": [2022, 7, 27],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 250,
      "transactionType": {
        "id": 2,
        "code": "savingsAccountTransactionType.withdrawal",
        "value": "Withdrawal",
        "deposit": false,
        "dividendPayout": false,
        "withdrawal": true,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 7, 27],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 1.000000,
      "runningBalance": 9.000000,
      "reversed": false,
      "transfer": {
        "id": 60,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 1.000000,
        "transferDate": [2022, 7, 27],
        "transferDescription": "Savings "
      },
      "submittedOnDate": [2022, 7, 27],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    },
    {
      "id": 249,
      "transactionType": {
        "id": 1,
        "code": "savingsAccountTransactionType.deposit",
        "value": "Deposit",
        "deposit": true,
        "dividendPayout": false,
        "withdrawal": false,
        "interestPosting": false,
        "feeDeduction": false,
        "initiateTransfer": false,
        "approveTransfer": false,
        "withdrawTransfer": false,
        "rejectTransfer": false,
        "overdraftInterest": false,
        "writtenoff": false,
        "overdraftFee": true,
        "withholdTax": false,
        "escheat": false,
        "amountHold": false,
        "amountRelease": false
      },
      "accountId": 96,
      "accountNo": "MSA000000096",
      "date": [2022, 7, 27],
      "currency": {
        "code": "KES",
        "name": "Kenyan Shilling",
        "decimalPlaces": 2,
        "inMultiplesOf": 1,
        "displaySymbol": "KSh",
        "nameCode": "currency.KES",
        "displayLabel": "Kenyan Shilling (KSh)"
      },
      "amount": 10.000000,
      "runningBalance": 10.000000,
      "reversed": false,
      "transfer": {
        "id": 59,
        "reversed": false,
        "currency": {
          "code": "KES",
          "name": "Kenyan Shilling",
          "decimalPlaces": 2,
          "inMultiplesOf": 1,
          "displaySymbol": "KSh",
          "nameCode": "currency.KES",
          "displayLabel": "Kenyan Shilling (KSh)"
        },
        "transferAmount": 10.000000,
        "transferDate": [2022, 7, 27],
        "transferDescription": "Savings"
      },
      "submittedOnDate": [2022, 7, 27],
      "interestedPostedAsOn": false,
      "submittedByUsername": "mifos"
    }
  ]
};
